spring:
  cache:
    cache-names:
      - cardsTheName
      - cardsImagesByName
      - cardsByExactName
      - setsByCode
      - autocomplete
      - allSets
      - cardsByCode
    caffeine:
      spec: maximumSize=500,expireAfterWrite=24h
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"